name: educaia
description: Plataforma de aprendizado personalizada
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.4.0
  http: ^1.3.0
  youtube_player_flutter: ^9.1.1
  markdown_widget: ^2.3.2+6
  provider: ^6.1.4
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  googleapis: ^14.0.0
  youtube_player_iframe: ^5.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png